server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false
    username: root
    password: Lutong~918

  application:
    # 服务名称
    name: content-center
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
        # 命名空间 dev
        namespace: 6b0e9c31-3145-411d-bf5f-439f90a03ad2
        cluster-name: BJ
        # k: v形式的元数据信息配置
        metadata:
          # 自己实例版本
          version: v1
          # 允许调用者的实例版本
          target-version: v1


# 这种是通过配置的方式实现Ribbon在对某个服务调用时候的自定义配置,比如这个负载均衡算法
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 指定为user-center开启饥饿加载, 多个 , 分割
ribbon:
  eager-load:
    clients: user-center
    enabled: true

# 日志
logging:
  level:
    top.lothar.contentcenter.feignclient.UserCenterFeignClient: debug

# feign配置方式去打印日志,要把@FeignClient注解上的configuration配置类去掉
#feign:
#  client:
#    config:
#      user-center:
#        loggerLevel: full
