server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false
    username: root
    password: Lutong~918

  application:
    # 服务名称
    name: content-center
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
