server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/content_center?useSSL=false
    username: root
    password: Lutong~918

  application:
    # 服务名称
    name: content-center
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: localhost:8848
        cluster-name: BJ

# 这种是通过配置的方式实现Ribbon在对某个服务调用时候的自定义配置,比如这个负载均衡算法
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# ribbon 指定为user-center开启饥饿加载, 多个 , 分割
ribbon:
  eager-load:
    clients: user-center
    enabled: true
